### ISSUE TITLE
[Balancing] Some feedback after testing your items

### ISSUE THREAD

**Issue by Aerity** [TheMysticSword/MysticsItems#101]
Hi ! First of all I really like most of the ideas you have for your items, plus you put extra effort to actually do models for the items. So I wanted to give you some feedback after thoroughly testing your mod !
 
[Spine Implant] : Feels good to use, situationnal as all whit items should be. Is there any sound feedback like for the Repulsive Armor ? If not it might be good to add some. (I'm not sure as I tested it with other mods) Might be a bit too good with characters like the Enforcer !

[Scratch Ticket] : It feels quite strong for a white Item, if you put it as green you can make it a bit more powerful but the fact that it affects all allies feels quite good already.

[Relentless Vendetta] It's a really cool item but it feels a bit too dependent on other items such as drones or specific equipment. I don't really know how to fix this while keeping the idea alive though 😅 

[Contraband Gunpowder] This one feels really weak sadly. I really love the idea to add some explosions here and there but it's not really good because you need to actually kill enemies to have a chance to activate it. I thought about a few ideas for this one : the first would be to make it a on-hit proc item, but it would make it feel a lot like will'o and other explosive items. Another idea would be that the item actually gets stacks everytime you pick up a powder flask and then it explodes for damage when you get hit/use an equipment. Last one would be a Lunar conversion for this item : ennemies have more chance to drop pickups but pickups explode when they do drop. Tell me how you feel about this !

[Faulty Spotter] Once again great idea, it feels really powerful however ! Maybe turn the crit chance down to 50% ? I'd have to playtest it more to give you an accurate percentage.

[Crystallized World] This is craaaazy good. I know red items are supposed to be op but 7 seconds freeze is bonkers ! Especially considering the fact that enemies can be killed way quicker that way. 1.5-2 seconds would already be enough tbh, especially considering the size of the teleporter ! So yeah, shorter freeze would feel more balanced.

[Timely Execution] 6 seconds of invincibility feels like a lot in this game, but the fact that it's a really situationnal item makes it feel balanced.

[Treasure Map] This one feel quite underpowered, waiting 2 minutes in the same spot is probably too difficult to make it really usable, especially considering that you need to farm to open the chest after this. I really like the idea though ! You could maybe turn this into some sort of OP rusty key or something. Like it grants access to a chest with a red item in it but the item disappear when you open the chest. (Of course you can't get another treasure map inside that chest)

[Rift Lens] I think the slow is really annoying and turns this good idea into a average one. Maybe make the character take double damage or something ? Like some chest addict that doesn't feel safe without having found his free chest. Also maybe add some feedback to the free chest like the rusted key chest !

[Gate Chalice] While I like the general Idea behind it, being able to skip a stage/boss feels probably too powerful for a 140s cooldown, I'd say it should be around 180-200s. Otherwise the feeling for this one is the same as the rift lens, you should probably turn it into an effect that can stack like the Tonic Affliction !

[Ratio Equalizer] This item is so good !! Crazy good even, being able to heal yourself so much if used properly is making it op, especially with a 20s cooldown. A 35-45s cooldown would probably make this more balanced.

And that's it for me ! I really like your ideas, please keep up with the good work and tell me if my feedback was useful or not !
(I'd be happy to playtest stuff for you if you ever need help !!)

**Comment by TheMysticSword** [comment]
Hi, thanks for trying the mod out and for the feedback! I'll try to reply to everything.

Spine Implant - yeah, there is both visual and audio feedback when it triggers (red shiny sparks come out of your back and a metallic sound plays). Maybe I should make these effects more noticable, I dunno.

Scratch Ticket - my friend (who made 90% of the models) kept bugging me that the item is terrible so that's why now it gives the amount of money equal to the final shrine price instead of a flat amount like $40.

Relentless Vendetta - well, that's the point of the item, to give you a period of time where you are extremely powerful to avenge the fallen friends you've made along the way, be it your co-op buddies or your drones. Also gives another incentive to buy drones!

Gunpowder - actually, it's really powerful! The idea is that it synergizes with other pickup-dropping items like the Monster Tooth, Ghor's Tome, Bandolier, Donut, etc., which potentially makes it even stronger than Will-o'-the-Wisp.

Faulty Spotter - I think it's fine - it's essentially an Ocular HUD, but on lower cooldown, but you don't choose what enemy it picks, so I think it balances itself out. And I think it's good to have powerful items, that incentivizes the player to actively seek them out.

Crystallized World - yeahhh, maybe 7 seconds is a bit of an overkill. I haven't got this item as a natural drop yet so I can't say for sure. I'll get it eventually and then we'll see!

Treasure Map - this is an interesting topic of discussion, as there are actually people that think the item is OP *and* there are other people who think it's underpowered! I think waiting 2 minutes is okay because you'd get enough gold by the time you unburrow the chest. Besides, it's a red every stage!

Rift Lens - I think it's fine. The slow is the lunar downside of the item which prevents it from being a busted OP lunar like Transcendence and Gesture of the Drowned. By the way, there's actually a unique sound effect when you open the rift chest! Maybe I'll add a visual effect eventually.

Gate Chalice - again, some people say it's too good, some say it's too bad. The debuff actually stacks if you skip multiple stages in a row without clearing the teleporter.

Ratio Equalizer - I felt like people were sleeping on it because of the long 45s cooldown, but I guess it's too good now! I'll play with it later and see if this change needs to be reverted.

**Comment by TheMysticSword** [comment]
Also, I'll probably set up a discussion board for this kind of stuff so that we don't need to discuss balancing in issues because I don't know at which point this issue is worth closing

**Comment by TheMysticSword** [comment]
Closing all suggestion/enhancement/balancing/feedback issues. A new, actual discussion board will be set up after the next mod update.
