### ISSUE TITLE
Can't load Mod

### ISSUE THREAD

**Issue by stealthmosquito** [TheMysticSword/MysticsItems#105]
[Error  : Unity Log] BadImageFormatException: Could not resolve field token 0x040000e7, due to: Could not load type of field 'MysticsItems.Main+<>c:<>9__6_0' (1) due to: Could not resolve type with token 0100006d (from typeref, class/assembly On.RoR2.ContentManager, MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:On.RoR2.ContentManager member:(null) signature:<none> assembly:C:\Users\Jaccoon\AppData\Roaming\Thunderstore Mod Manager\DataFolder\RiskOfRain2\profiles\Default\BepInEx\plugins\TheMysticSword-MysticsItems\MysticsItemsPlugin.dll type:<>c member:(null) signature:<none>
Stack trace:
MysticsItems.MysticsItemsPlugin.Awake () (at <3aa45e2e023e4aa28b9cf60d4dc75531>:IL_0017)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

**Comment by gojlus** [comment]
+1
seems like most item mods are not working rn. (Classic items, Mysticsitems, and Sivsitems all aren't working currently)

[Info   :   BepInEx] Loading [MysticsItems 1.1.7]
[Error  : Unity Log] BadImageFormatException: Could not resolve field token 0x040000e7, due to: Could not load type of field 'MysticsItems.Main+<>c:<>9__6_0' (1) due to: Could not resolve type with token 0100006d (from typeref, class/assembly On.RoR2.ContentManager, MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:MMHOOK_Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:On.RoR2.ContentManager member:(null) signature:<none> assembly:C:\Users\redsc\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\Default\BepInEx\plugins\TheMysticSword-MysticsItems\MysticsItemsPlugin.dll type:<>c member:(null) signature:<none>
Stack trace:
MysticsItems.MysticsItemsPlugin.Awake () (at <3aa45e2e023e4aa28b9cf60d4dc75531>:IL_0017)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

[Message:   BepInEx] Chainloader startup complete
