### ISSUE TITLE
Shrine of the Legend optional for lategame modpacks?

### ISSUE THREAD

**Issue by Maritime-Alice** [TheMysticSword/MysticsItems#150]
I've found the shrine of the legend to be highly disruptive to my mod pack balanced for going for very long runs and would greatly appreciate a config option to disable it.

**Comment by TheMysticSword** [comment]
How is it disruptive if you aren't obligated to use it? It's also supposed to be very rare, so if you have a mod that makes them more common, then it's on that mod. I don't want to add an option for disabling them because it's nearly useless under normal circumstances and it would spoil the surprise for those who just want to disable certain items in the config.

**Comment by Maritime-Alice** [comment]
I guess I can play with the rules established that "oh if this thing appears you're not allowed to use it", but like, a config option doesn't have to say anything about what it does just a disable for structures added by the mod. Also being secretive about the shrine could be cool for some players but I found it just made it a lot harder for me to even figure out what mod added it and if I could disable it to improve the modpack's balance.

**Comment by GitHub6F3C3C** [comment]
I would understand keeping certain features in a mod secret, but that would only work if the initial content was highlighted (for example, a survivor mod doesn't need to explain the challenge behind a skin unlock, for it's up to the players to actually play the character and find out). In this case the mod is adding something completely different from what's advertised and would arguably benefit from pointing it out, aswell as avoid general confusions since that same question will be asked over and over. It's also good practice to let players decide which features they prefer to keep enabled or not.

**Comment by TheMysticSword** [comment]
Changed my mind. This option will be added in the next update.
