### ISSUE TITLE
Some mod incompatibility

### ISSUE THREAD

**Issue by sirzento** [TheMysticSword/MysticsItems#219]
The game starts to lag and spam NRE Errors. 
The lag is described by having 2 sec freezes every 5 secs so its nearly unplayable.

It happens when you teleport to the third stage. A simple way to reproduce this is by giving yourself around 50 items and kill the teleporter boss, port to stage 2 and kill the boss again and teleport to stage 3. After that the log file should be around 500kb big and gets bigger fast. The game was starting to lag when my log file was around 20mb big.

I did use following mods:

- BepInExPack by bbepis
- R2API by tristanmcpherson
- RadialPings by ThinkInvis
- ItemExchangeNotifier by MagnusMagnuson
- ShowDeathCause by NotTsunami
- HookGenPatcher by RiskofThunder
- BiggerBazaar by MagnusMagnuson
- BetterUI by XoXFaby
- ShareSuite by FunkFrog-and-Sipondo
- MysticsRisky2Utils by TheMysticSword
- MysticsItems by TheMysticSword
- RTAutoSprintEx by JohnEdwa
- TILER2 by ThinkInvis
- Enforcer by EnforcerGang
- ChefMod by Gnome
- SniperClassic by EnforcerGang
- PaladinMod by Paladin_Alliance
- 3rdRowCSS by TheTimesweeper
- ClassicItems by ThinkInvis 

When I remove your lib + mysticItems, the NRE error doesn't happen and the game runs fine. I can rule out incompatibility with classic items because removing this mod will still result in NRE errors with your mod active.

Every mod is uptodate and dlc compatible.

Tested with:
- singleplayer without dlc
- multiplayer with dlc

Modpack code: Re9ygjCe9

[LogOutput Client (Not full log file).log](https://github.com/TheMysticSword/MysticsItems/files/8274792/LogOutput.Client.Not.full.log.file.log)
[LogOutput Host (Full log file).log](https://github.com/TheMysticSword/MysticsItems/files/8274794/LogOutput.Host.Full.log.file.log)
[LogOutput SP with cheat mod.log](https://github.com/TheMysticSword/MysticsItems/files/8274791/LogOutput.SP.with.cheat.mod.log)
W

**Comment by TheMysticSword** [comment]
Aerolt is causing this. Not something I can fix. I've reported it to the dev just now. Gonna keep the issue open for other people to see until it gets fixed.

**Comment by williamck123** [comment]
I'm having this same issue, but don't have Aerolt installed.

My mod list is:
-BepinInExPack
-HookGenPatcher
-R2API
-TILER2
-MysticsRisky2Utils
-MysticsItems
-ZetAspects
-Artifact_of_potential
-Enforcer
-SniperClassic
-BetterUI
-ScrollableLobbyUI
-PaladinMod
-MinerUnearthed
-Refightilization
-SacrificeVoidCradles
-ChefMod
-MobileTurretBuff
-ItemStatsMod
-HAND_OVERCLOCKED
-RedsSacrifice
-UntitledDifficultyMod
-BubbetsItems
-MMHOOK_Standalone
-ChensHelpers
-ChensGradiusMod
-ClassicItems
-ChensClassicItems
-EngiTurretTweak
-ArtificerExtended
-ChensMinionRetarget
-ChillDrone
-Dancer
-AurelionSol
-KingModUtilities
-Goku
-Trunks
-Vegeta
-SurvivorSortOrder
-Synergies

I know for sure Synergies isn't the problem, this was happening before. I also know that this a multiplayer exclusive problem, because it only happens when I join my friend's game, not in singleplayer. I think it might be something to do with ClassicItems? I don't know.
