### ISSUE TITLE
Having Bubbet's Items mod installed causes items in Mystic's Items to stop giving shield

### ISSUE THREAD

**Issue by HShotc** [TheMysticSword/MysticsItems#289]
When Bubbet's Items is installed, the Wireless Voltmeter and Shield Charger Upgrade Module don't give their shield at all.
Tested with default configurations for both mods and with only the two mods installed.

Code for the profile I used to test the mods:
018d42b9-9282-a78d-d899-1c229afde251

Log file for session where I confirmed the details of this issue:
[LogOutput.log](https://github.com/TheMysticSword/MysticsItems/files/14058267/LogOutput.log)

**Comment by TheMysticSword** [comment]
This is an issue with all kinds of shield-related items that rely on RecalculateStatsAPI if Bubbet's Items are installed. The same bug happens if you have only Bubbet's Items and Starstorm 2, for example.
This bug actually seems to be fixed in Bubbet's code, it's just that the mod hasn't been updated to their actual in-dev version yet.

**Comment by AmbassadorPineapple** [comment]
Fascinating...
