### ISSUE TITLE
[Suggestion/Balancing] All of my item suggestions in one issue, since I didn't want to fill the git.

### ISSUE THREAD

**Issue by Coffe-e** [TheMysticSword/MysticsItems#31]
Keep in mind, all of these are just what I think of the items, and how i'd change them. Feel free to explain why certain items are the way they are, so I can better understand what you're going for!

**[Visual/Audio Change]**
Contraband Gunpowder: Change the VFX to something less obscuring, as it can be a bit harsh on the eyes
Relentless Vendetta: Reduce the volume of the noise a bit.
Vintage Microphone: Lower the volume a bit, it can be a bit loud at times.

**[Basic Changes]**
Spine Implant: Buff the armor gain, since it's a bit weak
Tactical Scope: Small stacking damage buff for double-tap.
Relentless Vendetta: A small stacking buff to the same-stage rage's duration. 0.5 to 1 second would be good

**[All suggestions here are due to the fact that the item is unusable if you can't obtain the very specific condition they have]**
Doughnut: Either make it an on-interact and nerf heals, or make it guarantee barrel spawns in some way.
Scratch Ticket: Make it guarantee a chance shrine on the stage.
Mysterious Monolith: Guaranteed random shrine?

**[Reworks]**
Proximity Nanobots: Bolts immediately correct their path towards any enemies within 2.5m [+1.25m] (Numbers subject to change)

**[Reasoning]**
Proximity Nanobots: This item's effect is just not that good. An experienced player will rarely ever miss, and even when they do, the damage will barely matter since it scales so hard.

**Comment by TheMysticSword** [comment]
**[Visual/Audio Change]**
I tried addressing the Contraband Gunpowder visuals in the latest update, but I guess I can reduce the visual effect even more to just the orange ring and maaaaybe really small smoke particles (because the ring can sometimes go behind your screen and you wouldn't even notice the item proc).
Sounds - noted. I tried to keep them at the same level as the vanilla SFX but looks like I made some mistakes.

**[Basic Changes]**
Spine Implant - sure, I'll bump up the stats to 10 (+10 per stack)!
Tactical Scope - I'll think about this one. I don't like the idea of items giving you a flat buff to stats without any condition. That's boring item design, and completely uninteractive.
Relentless Vendetta - sure! The same-stage death behaviour was a last minute decision to prevent it from becoming overpowered with Squid Polyps, but I agree that it feels bad when you get a lot of one item but the further stacks don't matter.

**[All suggestions here are due to the fact that the item is unusable if you can't obtain the very specific condition they have]**
*Not* finding barrels or shrines is normal only for hidden realms and the final stage. The items are there to fill the niches of their interactables (barrels - now you have a reason to open them past the first 2 stages; shrines - feels nice when you get back at least a little bit of the money you spent, in rare cases it can even give you a profit).
The Monolith is too powerful for buffing in my opinion. Even with one of them, you get *another* item from chance and mountain shrines and *double* gold from combat shrines. Isn't that, like, really good?

**[Reworks]**
I generally hate effects that make you shoot *not* where you aim at. Double Vision from EtG comes to mind, but that one is an active ability and is not forced onto you for the rest of the run.

**Comment by Coffe-e** [comment]
> 
> 
> **[Visual/Audio Change]**
> I tried addressing the Contraband Gunpowder visuals in the latest update, but I guess I can reduce the visual effect even more to just the orange ring and maaaaybe really small smoke particles (because the ring can sometimes go behind your screen and you wouldn't even notice the item proc).
> Sounds - noted. I tried to keep them at the same level as the vanilla SFX but looks like I made some mistakes.
> 
> **[Basic Changes]**
> Spine Implant - sure, I'll bump up the stats to 10 (+10 per stack)!
> Tactical Scope - I'll think about this one. I don't like the idea of items giving you a flat buff to stats without any condition. That's boring item design, and completely uninteractive.
> Relentless Vendetta - sure! The same-stage death behaviour was a last minute decision to prevent it from becoming overpowered with Squid Polyps, but I agree that it feels bad when you get a lot of one item but the further stacks don't matter.
> 
> **[All suggestions here are due to the fact that the item is unusable if you can't obtain the very specific condition they have]**
> _Not_ finding barrels or shrines is normal only for hidden realms and the final stage. The items are there to fill the niches of their interactables (barrels - now you have a reason to open them past the first 2 stages; shrines - feels nice when you get back at least a little bit of the money you spent, in rare cases it can even give you a profit).
> The Monolith is too powerful for buffing in my opinion. Even with one of them, you get _another_ item from chance and mountain shrines and _double_ gold from combat shrines. Isn't that, like, really good?
> 
> **[Reworks]**
> I generally hate effects that make you shoot _not_ where you aim at. Double Vision from EtG comes to mind, but that one is an active ability and is not forced onto you for the rest of the run.

Yeah,

**Comment by TheMysticSword** [comment]
"Yeah,"
Enough said, haha

**Comment by Coffe-e** [comment]
I also didn't mean to close the issue, so i'll fix that too

**Comment by Coffe-e** [comment]
But yeah. I agree with stuff like the Tactical sight and proxy nanobot, but I do think they should be looked into for more useful effects, since they're pretty minor for both how you obtain them, and their power compared to other whites (Since the character items are operating on item rarities).

Most of those are just things I spitballed, and would be starting points for ideas, but depending on what you want it could change to anything really.

I'd love to talk more, potentially on discord, but It's like 4am rn and I gotta sleep lol.
If you wanna talk more, hmu at TEA#9790

**Comment by danielkillsya2** [comment]
For Contrabrand Gunpowder, Is it possible to make it explode on pickup expired, maybe a bit weaker than if you picked it up normally? Could make it scale with amount of time left, making it so it still does something if you can't get close to it.
I found with low mobility characters, I can't risk going to pick it up and a fair amount of the procs go to complete waste.

**Comment by TheMysticSword** [comment]
Buffed Spine Implant, re-adjusted some of the sfx, reduced the gunpowder vfx, made same-stage rage on Vendetta stackable.
Contaband Gunpowder flasks now drop only on kill, but with 100% chance, no longer roll on the ground, and disappear after 60 seconds instead of 10. Closing this for now.
By the way, I recommend making separate issues because it's easier to track progress that way, and we don't need to write walls of text to discuss every single topic.

**Comment by Coffe-e** [comment]
Yeah, I gotcha. I was just worried about flooding the git, but i'll keep that in mind.
By the way, is it possible to suggest item ideas in this git, or should that be something that's dmed to you?

**Comment by TheMysticSword** [comment]
Just added a discussion category for item ideas, I recommend using that https://github.com/TheMysticSword/MysticsItems/discussions/categories/item-ideas
